export const HTTP_404_ERROR = "HTTP_404_ERROR";
export const HTTP_500_ERROR = "HTTP_500_ERROR";

export const FETCH_ACCOUNTS_PENDING = "FETCH_ACCOUNTS_PENDING";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_ERROR = "FETCH_ACCOUNTS_ERROR";
export const CLEAN_ACCOUNTS = "CLEAN_ACCOUNTS";

export const CREATE_ACCOUNT_PENDING = "CREATE_ACCOUNT_PENDING";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_ERROR = "CREATE_ACCOUNT_ERROR";

export const FETCH_ACCOUNT_PENDING = "FETCH_ACCOUNT_PENDING";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_ERROR = "FETCH_ACCOUNT_ERROR";
export const CLEAN_ACCOUNT = "CLEAN_ACCOUNT";

export const FETCH_TRANSACTIONS_PENDING = "FETCH_TRANSACTIONS_PENDING";
export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_ERROR = "FETCH_TRANSACTIONS_ERROR";
export const CLEAN_TRANSACTIONS = "CLEAN_TRANSACTIONS";

export const CREATE_TRANSACTION_PENDING = "CREATE_TRANSACTION_PENDING";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_ERROR = "CREATE_TRANSACTION_ERROR";

export const FETCH_TRANSACTION_PENDING = "FETCH_TRANSACTION_PENDING";
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";
export const FETCH_TRANSACTION_ERROR = "FETCH_TRANSACTION_ERROR";
export const CLEAN_TRANSACTION = "CLEAN_TRANSACTION";

export const FETCH_TRIAL_BALANCE_PENDING = "FETCH_TRIAL_BALANCE_PENDING";
export const FETCH_TRIAL_BALANCE_SUCCESS = "FETCH_TRIAL_BALANCE_SUCCESS";
export const FETCH_TRIAL_BALANCE_ERROR = "FETCH_TRIAL_BALANCE_ERROR";
export const FETCH_PROFIT_LOSS_PENDING = "FETCH_PROFIT_LOSS_PENDING";
export const FETCH_PROFIT_LOSS_SUCCESS = "FETCH_PROFIT_LOSS_SUCCESS";
export const FETCH_PROFIT_LOSS_ERROR = "FETCH_PROFIT_LOSS_ERROR";
export const FETCH_BALANCE_SHEET_PENDING = "FETCH_BALANCE_SHEET_PENDING";
export const FETCH_BALANCE_SHEET_SUCCESS = "FETCH_BALANCE_SHEET_SUCCESS";
export const FETCH_BALANCE_SHEET_ERROR = "FETCH_BALANCE_SHEET_ERROR";
export const CLEAN_STATEMENT = "CLEAN_STATEMENTS";